### PR TITLE
Adding ARM Template for AspNetCore Service Fabric

### PR DESCRIPTION
**Pull request by kuvinodms**
Here is the Diff link between existing ArmTemplate and the updated one:
https://www.diffchecker.com/5JNlPvmW

### CODE REVIEW

**Comment by bishal-pdMSFT** [comment]
+1 for Himanshu' comment

**Comment by bishal-pdMSFT** [comment]
Do you need KV ARM template also, or will that be created as an asset ?

**Comment by kuvinodms** [comment]
@hiyadav Yes, we need to do that as well but as a part of different story.
@bishal-pdMSFT KV and certificates will be created as an asset.,

**Comment by hiyadav** [comment]
@kuvinodms better if that change is done before merging this, or they can be merged together as well.

**Comment by kuvinodms** [comment]
@hiyadav definitely not together, but it make sense to do that change before merging this.

**Comment by kuvinodms** [comment]
@hiyadav Addressed your comment by correcting the servicefabric folder structure. Let me know if you have any other comment/suggestion with the PR.
@bishal-pdMSFT Please read Himanshu's 1st comment again to get clarity over context. Since it is resolved now, kindly let me know if you have any comment/suggestion with PR.

**Pull request merged**
