### PR TITLE
Replicated container folder python django for containerWithTests

### PR DESCRIPTION
**Pull request by vagisha-nidhi**

### CODE REVIEW

**Comment by ShreyasRmsft** [comment]
@bishal-pdMSFT, the realization hit me a little later that if we replicated the folder first as is with no changes and then sent an incremental PR for the changed files, reviewing will be much simpler.

This is the first PR where I've asked Vagisha to just replicate the folder with no changes whatsoever

**Comment by bishal-pdMSFT** [comment]
@ShreyasRmsft if this is same as existing folder, I will go ahead and merge it.

**Comment by ShreyasRmsft** [comment]
@vagisha-nidhi please confirm whether @bishal-pdMSFT can go ahead and merge this. Double check if the files have been duplicated as is and no new files have been added

**Comment by bishal-pdMSFT** [comment]
@vagisha-nidhi please update the other PR as well with latest mater

**Pull request merged**
